name: Branch Selection

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to proceed with'
        required: true
        default: 'main'
        type: choice
        options:
          - dev
          - test
          - ite
          - prod

jobs:
  select-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Set selected branch
        run: echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_ENV

  run-workflow:
    needs: select-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run DEV Environment Commands
        if: env.branch == 'dev'
        run: echo "Running commands for DEV environment"

      - name: Run TEST Environment Commands
        if: env.branch == 'test'
        run: echo "Running commands for TEST environment"

      - name: Run ITE Environment Commands
        if: env.branch == 'ite'
        run: echo "Running commands for ITE environment"

      - name: Run PROD Environment Commands
        if: env.branch == 'prod'
        run: echo "Running commands for PROD environment"
