name: "Example Solution Workflow"

on:
  workflow_dispatch:
    inputs:
      TDV_Environment:
        type: choice
        description: "Select the environment of the TDV server"
        options:
          - dev
          - TEST
          - ITE
          - PROD
        default:
          dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Solution Repository
        uses: actions/checkout@v4
        with:
          repository: Ash210611/silverton-solution-brutesquad-example
          path: solution-repo

      - name: Set Environment Variables
        run: echo "CONFIG_FILE=${{ inputs.TDV_Environment }}.liquibase" >> $GITHUB_ENV

      - name: Create Destination Directory
        run: mkdir -p ${{ github.workspace }}/config

      - name: Copy TDV DDL Configuration File
        run: cp solution-repo/data_ops_blueprints_tdv_ddl/config/${{ inputs.TDV_Environment }}/liquibase.properties ${{ github.workspace }}/config

      - name: Copy TDV DML Configuration File
        run: cp solution-repo/data_ops_blueprints_tdv_dml/config/${{ inputs.TDV_Environment }}/liquibase.properties ${{ github.workspace }}/config

      - name: Copy TDV DDL Change Log File
        run: cp solution-repo/data_ops_blueprints_tdv_ddl/${{ inputs.TDV_Environment }}.changelog.xml ${{ github.workspace }}/config

      - name: Copy TDV DDL Change Log File
        run: cp solution-repo/data_ops_blueprints_tdv_dml/${{ inputs.TDV_Environment }}.changelog.xml ${{ github.workspace }}/config

      - name: Checkout DataOps Repository
        uses: actions/checkout@v4
        with:
          repository: Ash210611/silverton-dataops-brutesquad-exapmle
          path: dataops-repo

      - id: OPS-action
        uses: Ash210611/silverton-dataops-brutesquad-exapmle@main
        with: 
          TDV_USER: ${{ secrets.TDV_SERV_USER_DEV }}
          TDV_PASSWORD: ${{ secrets.TDV_SERV_PASSWORD_DEV }}
          TDV_ENV: ${{ inputs.TDV_Environment }}
          CONFIG_PATH: ${{ github.workspace }}/config/${{ env.CONFIG_FILE }}
