name: "Example Solution Workflow - Main New"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    inputs:
      LIQUIBASE_COMMAND:
        description: 'Liquibase Command to run'
        required: true
        default: 'status'
        type: choice
        options:
          - status
          - validate
          - update
          - rollback
      OPS_TYPE:
        description: 'OPS Type. DDL, DML or Stored Procedure'
        required: true
        default: 'tdv_ddl'
        type: choice
        options:
          - tdv_ddl
          - tdv_dml
          - stored_proc
          - all
      TDV_Environment:
        description: 'The environment of TDV server to deploy to'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - UAT
          - PRD
      RUN_RULES_ENGINE:
        description: 'Run Rules Engine on the Solutions'
        required: true
        default: false
        type: boolean
      USE_LIQUIBASE_TAG:
        description: 'Use the tag to assign on the liquibase. This must be true for Rollback action.'
        required: true
        default: false
        type: boolean
      LIQUIBASE_TAG:
        description: 'The tag used by liquibase commands such as rollback.'
        required: false
        default: 'default'
        type: string

env:
  LQUIBASE_COMMAND: ${{ inputs.LIQUIBASE_COMMAND || 'status' }}
  OPS_TYPE: ${{ inputs.OPS_TYPE || 'tdv_ddl' }}
  TDV_ENV: ${{ inputs.TDV_Environment || 'DEV' }}
  RUN_RULES_ENGINE: ${{ inputs.RUN_RULES_ENGINE || false }}
  ASSIGN_LIQUIBASE_TAG: ${{ inputs.ASSIGN_LIQUIBASE_TAG || false }}
  LIQUIBASE_TAG: ${{ inputs.LIQUIBASE_TAG || 'default' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Solution Repository
        uses: actions/checkout@v4
        with:
          repository: Ash210611/silverton-solution-brutesquad-example-main
          path: solution-repo
      
      - name: Checkout DataOps Repository
        uses: actions/checkout@v4
        with:
          repository: Ash210611/silverton-dataops-brutesquad-exapmle
          path: dataops-repo

      - id: OPS-action
        uses: Ash210611/silverton-dataops-brutesquad-exapmle/action1@main
        with:
          TDV_USER: ${{ secrets.TDV_DEV_USERNAME }}
          TDV_PASSWORD: ${{ secrets.TDV_DEV_PASSWORD }}
          TDV_ENV: ${{ env.TDV_ENV }}
          LIQUIBASE_COMMAND: ${{ env.LQUIBASE_COMMAND }}
          OPS_TYPE: ${{ env.OPS_TYPE }}
          RUN_RULES_ENGINE: ${{ env.RUN_RULES_ENGINE }}
          ASSIGN_LIQUIBASE_TAG: ${{ inputs.ASSIGN_LIQUIBASE_TAG || false }}
          LIQUIBASE_TAG: ${{ env.LIQUIBASE_TAG }}
