name: "Example Solution Workflow - Main New"

on:
  workflow_dispatch:
    inputs:
      TDV_Environment:
        type: choice
        description: "Select the environment of the TDV server"
        options:
          - dev
          - TEST
          - ITE
          - PROD
        default:
          dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Solution Repository
        uses: actions/checkout@v4
        with:
          repository: Ash210611/silverton-solution-brutesquad-example-main
          path: solution-repo
      
      - name: Checkout DataOps Repository
        uses: actions/checkout@v4
        with:
          repository: Ash210611/silverton-dataops-brutesquad-exapmle
          path: dataops-repo

      - id: OPS-action
        uses: Ash210611/silverton-dataops-brutesquad-exapmle/action1@main
        with: 
          TDV_USER: ${{ secrets.TDV_SERV_USER_DEV }}
          TDV_PASSWORD: ${{ secrets.TDV_SERV_PASSWORD_DEV }}
          TDV_ENV: ${{ inputs.TDV_Environment }}
          CONFIG_PATH: ${{ github.workspace }}/config/liquibase.properties
          CHANGE_LOG_FILE_PATH : ${{ github.workspace }}/config/${{ inputs.TDV_Environment }}.changelog.xml
